# Generated by Django 4.1.3 on 2022-12-10 11:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='color_type_of_procedure',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Overall Color', 'Overall Color'), ('Frame Foil', 'Frame Foil'), ('Full Foil', 'Full Foil'), ('Partial Foil', 'Partial Foil'), ('Balayage', 'Balayage'), ('Root Smudge', 'Root Smudge'), ('Gloss', 'Gloss')], max_length=30, null=True, verbose_name='Type of hair coloring'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='comment_about_haircut',
            field=models.TextField(blank=True, null=True, verbose_name='Comment about haircut'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='comment_about_styling',
            field=models.TextField(blank=True, null=True, verbose_name='Comment about hair styling'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='cut_type_of_procedure',
            field=models.CharField(blank=True, choices=[("Women's haircut", "Women's haircut"), ("Men's haircut", "Men's haircut"), ("Child's haircut", "Child's haircut")], max_length=16, null=True, verbose_name='Haircut type'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='main_type_of_procedure',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cut', 'Cut'), ('Color', 'Color'), ('Blow', 'Blow'), ('Styling', 'Styling'), ('Treatments', 'Treatments')], max_length=1000, verbose_name='Main type of procedure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='other_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Other comments'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='product_used_for_color',
            field=models.TextField(blank=True, null=True, verbose_name='Products used for coloring'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='product_used_for_treatment',
            field=models.TextField(blank=True, null=True, verbose_name='Products used for treatment'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='styling_type_of_procedure',
            field=models.CharField(blank=True, choices=[('Bridal hairstyle', 'Bridal hairstyle'), ('Formal hairstyle', 'Formal hairstyle'), ('Hair curling', 'Hair curling'), ('Bun curling', 'Bun curling')], max_length=17, null=True, verbose_name='Hair styling services'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='treatment_type_of_procedure',
            field=models.CharField(blank=True, choices=[('KERATIN therapy', 'KERATIN therapy'), ('ARGAN therapy', 'ARGAN therapy'), ('PROTEIN therapy', 'PROTEIN therapy')], max_length=16, null=True, verbose_name='Treatment procedure'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='washing_hair',
            field=models.BooleanField(blank=True, verbose_name='Is hair washing included? (Yes/No)'),
        ),
    ]
