# Generated by Django 4.1.3 on 2022-12-17 11:45

import beauty_salon_manage_sistem.core.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_alter_procedure_color_type_of_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='after_image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[beauty_salon_manage_sistem.core.validators.validate_image_size], verbose_name='after images'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='before_image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[beauty_salon_manage_sistem.core.validators.validate_image_size], verbose_name='before images'),
        ),
    ]
