# Generated by Django 4.1.3 on 2022-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[("L'Oreal", "L'Oreal"), ('Joico', 'Joico'), ('MOROCCANOIL', 'MOROCCANOIL')], max_length=150, verbose_name='Brand:')),
                ('type_of_product', models.CharField(max_length=150, verbose_name='Product type:')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Serial number:')),
                ('grams', models.PositiveIntegerField(verbose_name='Volume(grams):')),
                ('image_of_product', models.URLField(verbose_name='Product image:')),
            ],
        ),
    ]
