# Generated by Django 4.1.3 on 2022-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('grams', models.PositiveIntegerField()),
                ('image_of_product', models.URLField()),
            ],
        ),
    ]
