# Generated by Django 4.1.3 on 2022-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addproducts',
            options={'verbose_name_plural': 'Product list'},
        ),
    ]
