# Generated by Django 4.1.3 on 2022-11-22 14:27

import beauty_salon_manage_sistem.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppStaffProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), beauty_salon_manage_sistem.core.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), beauty_salon_manage_sistem.core.validators.validate_only_letters])),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='AppCustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), beauty_salon_manage_sistem.core.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), beauty_salon_manage_sistem.core.validators.validate_only_letters])),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11)),
                ('hair_type', models.CharField(choices=[('Straight hair', 'Straight hair'), ('Wavy hair', 'Wavy hair'), ('Curly hair', 'Curly hair'), ('Kinky hair', 'Kinky hair'), ('I am not sure', 'I am not sure')], max_length=13)),
                ('hair_long', models.CharField(choices=[('Short hair', 'Short hair'), ('Middle hair', 'Middle hair'), ('Long hair', 'Long hair'), ('Very long hair', 'Very long hair'), ('I am not sure', 'I am not sure')], max_length=14)),
                ('further_explanation', models.TextField(blank=True, max_length=250, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hair_stylist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
    ]
