# Generated by Django 4.1.3 on 2022-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcustomeruser',
            name='choose_hair_stylist',
            field=models.CharField(choices=[('person.get_full_name', 'Koko Boko'), ('person.get_full_name', 'Riki MIki')], default='1', max_length=300),
            preserve_default=False,
        ),
    ]
