# Generated by Django 4.1.3 on 2022-12-07 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbaseuser',
            name='date_joined',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appbaseuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appcustomeruser',
            name='hair_stylist',
            field=models.ManyToManyField(to='accounts.appstaffprofile', verbose_name='Hair stylist:'),
        ),
        migrations.AlterField(
            model_name='appbaseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
