# Generated by Django 4.1.3 on 2022-12-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appbaseuser_date_joined_appbaseuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appbaseuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='appbaseuser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='appbaseuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
