# Generated by Django 4.1.3 on 2022-12-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appbaseuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appstaffprofile',
            options={'verbose_name': 'Staff Profile'},
        ),
    ]
