# Generated by Django 4.1.3 on 2022-12-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appstaffprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appbaseuser',
            options={'default_permissions': (), 'verbose_name': 'Staff User'},
        ),
    ]
