# Generated by Django 4.1.3 on 2022-12-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appbaseuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcustomeruser',
            options={'default_permissions': (), 'verbose_name': 'Customer'},
        ),
    ]
