# Generated by Django 4.1.3 on 2022-12-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appcustomeruser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcustomeruser',
            options={'verbose_name': 'Customer'},
        ),
    ]
